baseURL = "https://strangedays.no/"
languageCode = "no-nb"
title = "Strange Days"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "no"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Livet er som en banan"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-green"
  featured_image = "/images/sd-01.jpg"
  recent_posts_number = 2
